*&---------------------------------------------------------------------*
*&  Include           /PSYNG/BRIDGE_SYNCH_RULES_SS
*&---------------------------------------------------------------------*
SELECTION-SCREEN: FUNCTION KEY 1.
SELECTION-SCREEN: FUNCTION KEY 2.

*--SOD version block
SELECTION-SCREEN: BEGIN OF BLOCK vrsio WITH FRAME TITLE text-b00.

*--PLC ruleset ID field
PARAMETERS : p_plcvrs TYPE /psyng/sw_plc_ruleset.

SELECTION-SCREEN SKIP 1.

PARAMETERS :   p_vrsio TYPE /psyng/sodvrsio MEMORY ID /psyng/vrsio.

*  LINE
SELECTION-SCREEN: BEGIN OF LINE.
SELECTION-SCREEN: COMMENT 1(18) text-148 FOR FIELD p_crtver.
PARAMETERS :  p_crtver AS CHECKBOX USER-COMMAND ud.
SELECTION-SCREEN: COMMENT 24(16) text-149.
SELECTION-SCREEN: POSITION 41.
PARAMETERS : p_text(80) TYPE c LOWER CASE MODIF ID t1.
SELECTION-SCREEN: END OF LINE.





SELECTION-SCREEN: END OF BLOCK vrsio.

*--Pull/Push selection block
SELECTION-SCREEN: BEGIN OF BLOCK b1 WITH FRAME TITLE text-t01.

*  LINE : Radiobutton
SELECTION-SCREEN: BEGIN OF LINE.
PARAMETERS: p_pull RADIOBUTTON GROUP g1 USER-COMMAND radi DEFAULT 'X'.
SELECTION-SCREEN: COMMENT 2(60) text-t27 FOR FIELD p_pull.
SELECTION-SCREEN: END OF LINE.

*  LINE : Radiobutton
SELECTION-SCREEN: BEGIN OF LINE.
PARAMETERS: p_push RADIOBUTTON GROUP g1.
SELECTION-SCREEN: COMMENT 2(60) text-t28 FOR FIELD p_push.
SELECTION-SCREEN: END OF LINE.

SELECTION-SCREEN: END OF BLOCK b1.

*--Pull details block
*SELECTION-SCREEN: BEGIN OF BLOCK b2 WITH FRAME TITLE text-t02.

*  Ruleset
SELECTION-SCREEN: BEGIN OF BLOCK b4 WITH FRAME TITLE text-t16.
*    ABAP Application
SELECTION-SCREEN: BEGIN OF BLOCK b5 WITH FRAME TITLE text-t17.
PARAMETERS: p_sysid TYPE /psyng/api_sysid MODIF ID m1.
PARAMETERS: p_func AS CHECKBOX USER-COMMAND uc1 MODIF ID m1.
PARAMETERS: p_conf AS CHECKBOX MODIF ID m1.
SELECTION-SCREEN SKIP 1.
PARAMETERS p_val AS CHECKBOX USER-COMMAND uc2 MODIF ID m1.
SELECTION-SCREEN: END OF BLOCK b5.

SELECTION-SCREEN: END OF BLOCK b4.

*  Mitigation
SELECTION-SCREEN: BEGIN OF BLOCK b6 WITH FRAME TITLE text-t18.
PARAMETERS: p_mc_def AS CHECKBOX MODIF ID m1.
PARAMETERS: p_mc_ass AS CHECKBOX MODIF ID m1.
SELECTION-SCREEN: END OF BLOCK b6.

*SELECTION-SCREEN: END OF BLOCK b2.

*--Push details block
*SELECTION-SCREEN: BEGIN OF BLOCK b3 WITH FRAME TITLE text-x03.
SELECTION-SCREEN: BEGIN OF BLOCK b7 WITH FRAME TITLE text-t19.
SELECTION-SCREEN: BEGIN OF BLOCK b9 WITH FRAME TITLE text-t21.

*  LINE : Radio button
SELECTION-SCREEN: BEGIN OF LINE.
PARAMETERS: p_sysind RADIOBUTTON GROUP g2 USER-COMMAND radi1
             DEFAULT 'X' MODIF ID m2.
SELECTION-SCREEN: COMMENT 2(18) text-x04 FOR FIELD p_sysind MODIF ID m2.
SELECTION-SCREEN: END OF LINE.

*  LINE : Checkbox
SELECTION-SCREEN: BEGIN OF LINE.
SELECTION-SCREEN: POSITION 5.
PARAMETERS : p_schema AS CHECKBOX MODIF ID m2.
SELECTION-SCREEN: COMMENT 7(27) text-t22 MODIF ID m2.
SELECTION-SCREEN: END OF LINE.

*  LINE : Checkbox
SELECTION-SCREEN: BEGIN OF LINE.
SELECTION-SCREEN: POSITION 5.
PARAMETERS : p_group AS CHECKBOX MODIF ID m2.
SELECTION-SCREEN: COMMENT 7(28) text-t23 MODIF ID m2.
SELECTION-SCREEN: END OF LINE.

*  LINE : Checkbox
SELECTION-SCREEN: BEGIN OF LINE.
SELECTION-SCREEN: POSITION 5.
PARAMETERS: p_rule AS CHECKBOX USER-COMMAND rovrride MODIF ID m2.
SELECTION-SCREEN: COMMENT 7(28) text-t24 MODIF ID m2.
SELECTION-SCREEN: END OF LINE.

*  LINE : Checkbox
SELECTION-SCREEN: BEGIN OF LINE.
SELECTION-SCREEN: POSITION 7.
PARAMETERS : p_roride AS CHECKBOX MODIF ID m2.
SELECTION-SCREEN: COMMENT 9(14) text-150 MODIF ID m2.

SELECTION-SCREEN: END OF LINE.

*  LINE : Checkbox
SELECTION-SCREEN: BEGIN OF LINE.
SELECTION-SCREEN: POSITION 5.
PARAMETERS : p_actmod AS CHECKBOX MODIF ID m2.
SELECTION-SCREEN: COMMENT 7(39) text-t25 MODIF ID m2.
SELECTION-SCREEN: END OF LINE.

SELECTION-SCREEN: SKIP.

*  LINE : Radio button
SELECTION-SCREEN: BEGIN OF LINE.
PARAMETERS: p_sysdp RADIOBUTTON GROUP g2 MODIF ID m2.
SELECTION-SCREEN: COMMENT 2(18) text-x05 FOR FIELD p_sysdp MODIF ID m2.
SELECTION-SCREEN: END OF LINE.

*  LINE : Checkbox
SELECTION-SCREEN: BEGIN OF LINE.
SELECTION-SCREEN: COMMENT 7(6) text-t26 MODIF ID m2.
PARAMETERS: p_sys TYPE /psyng/bridge_system MODIF ID m2.
SELECTION-SCREEN: END OF LINE.

*  LINE : Checkbox
SELECTION-SCREEN: BEGIN OF LINE.
SELECTION-SCREEN: POSITION 5.
PARAMETERS: p_uacmod AS CHECKBOX USER-COMMAND amovrride MODIF ID m2.
SELECTION-SCREEN: COMMENT 7(40) text-189 FOR FIELD p_uacmod MODIF ID m2.
SELECTION-SCREEN: END OF LINE.

*  LINE : Checkbox
SELECTION-SCREEN: BEGIN OF LINE.
SELECTION-SCREEN: POSITION 7.
PARAMETERS : p_amorde AS CHECKBOX MODIF ID m2.
SELECTION-SCREEN: COMMENT 9(22) text-151 FOR FIELD p_amorde MODIF ID
m2.
SELECTION-SCREEN: END OF LINE.

*  LINE : Checkbox
SELECTION-SCREEN: BEGIN OF LINE.
SELECTION-SCREEN: POSITION 5.
PARAMETERS: p_grpcmp AS CHECKBOX USER-COMMAND gcovrride MODIF ID m2.
SELECTION-SCREEN: COMMENT 7(42) text-188 FOR FIELD p_grpcmp MODIF ID m2.
SELECTION-SCREEN: END OF LINE.

*  LINE : Checkbox
SELECTION-SCREEN: BEGIN OF LINE.
SELECTION-SCREEN: POSITION 7.
PARAMETERS : p_gcorde AS CHECKBOX MODIF ID m2.
SELECTION-SCREEN: COMMENT 9(24) text-152 FOR FIELD p_gcorde MODIF ID m2.
SELECTION-SCREEN: END OF LINE.

SELECTION-SCREEN: END OF BLOCK b9.
SELECTION-SCREEN: END OF BLOCK b7.

SELECTION-SCREEN: BEGIN OF BLOCK b8 WITH FRAME TITLE text-t20.
PARAMETERS: p_mc_d1 AS CHECKBOX MODIF ID m2.
PARAMETERS: p_mc_a1 AS CHECKBOX MODIF ID m2.
SELECTION-SCREEN: END OF BLOCK b8.
*SELECTION-SCREEN: END OF BLOCK b3.

*---Background Block
SELECTION-SCREEN: BEGIN OF BLOCK bgd_o WITH FRAME  .
SELECTION-SCREEN PUSHBUTTON  01(6) bgd_but USER-COMMAND bgd_but.
SELECTION-SCREEN COMMENT 16(50) text-b05 .
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN PUSHBUTTON  4(30) text-191 USER-COMMAND scjb
MODIF ID bgd.
SELECTION-SCREEN PUSHBUTTON  40(25) text-192 USER-COMMAND sm37
MODIF ID bgd.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN: END OF BLOCK bgd_o.
