*&---------------------------------------------------------------------*
*&  Include           ZARP_DISTRIBUTION_CFGSETS_SS
*&---------------------------------------------------------------------*

*--Configuration Set Publishing
SELECTION-SCREEN: BEGIN OF BLOCK publishb WITH FRAME TITLE text-b00.

*--Systems
SELECTION-SCREEN: BEGIN OF BLOCK sysb WITH FRAME TITLE text-b01.
SELECT-OPTIONS : s_system  FOR /psyng/sw_rfcdes-systid.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS : pf_cmbn TYPE flag AS CHECKBOX.
SELECTION-SCREEN COMMENT 5(38) text-b04 FOR FIELD pf_cmbn.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN: END OF BLOCK sysb.

*--Create new Configuration Set
SELECTION-SCREEN: BEGIN OF BLOCK cfgsetb WITH FRAME TITLE text-b02.
PARAMETERS :
  pf_trsfr TYPE flag AS CHECKBOX DEFAULT 'X',
  pf_pbset TYPE flag AS CHECKBOX DEFAULT 'X',
  pf_tstmd TYPE flag AS CHECKBOX.
SELECTION-SCREEN: END OF BLOCK cfgsetb.

*---sod version
SELECTION-SCREEN: begin of block sod with FRAME TITLE text-b06.
   PARAMETERS: pf_dflt  type flag as checkbox default 'X'
               USER-COMMAND abap MODIF ID rem,
               sodvrsio type /PSYNG/SODVRSIO MODIF ID rem.
SELECTION-SCREEN BEGIN OF LINE.
   PARAMETERS : p_inval TYPE flag AS CHECKBOX.
   SELECTION-SCREEN COMMENT 5(38) text-o13 FOR FIELD p_inval.
SELECTION-SCREEN End OF LINE.
   SELECTION-SCREEN: BEGIN OF LINE.
   SELECTION-SCREEN: COMMENT 1(75) text-o07.
   SELECTION-SCREEN: END OF LINE.
   SELECTION-SCREEN: BEGIN OF LINE.
   SELECTION-SCREEN: COMMENT 1(75) text-o08.
   SELECTION-SCREEN: END OF LINE.
   SELECTION-SCREEN: BEGIN OF LINE.
   SELECTION-SCREEN: COMMENT 1(75) text-o09.
   SELECTION-SCREEN: END OF LINE.
*   SELECTION-SCREEN : SKIP.
   SELECTION-SCREEN: BEGIN OF LINE.
   SELECTION-SCREEN: COMMENT 1(75) text-o10.
   SELECTION-SCREEN: END OF LINE.

   SELECTION-SCREEN: BEGIN OF LINE.
   SELECTION-SCREEN: COMMENT 1(75) text-o11.
   SELECTION-SCREEN: END OF LINE.
   SELECTION-SCREEN: BEGIN OF LINE.
   SELECTION-SCREEN: COMMENT 1(75) text-o12.
   SELECTION-SCREEN: END OF LINE.
   SELECTION-SCREEN: end of BLOCK sod.

*--Description
SELECTION-SCREEN: BEGIN OF BLOCK descb WITH FRAME TITLE text-b03.
*BOC by GSINGH on 08.02.2023 for B17171 - Changing the selection screen
*texts to 'Config Set'
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS :pf_cpyl TYPE flag AS CHECKBOX DEFAULT 'X'
        USER-COMMAND abap MODIF ID lp.
SELECTION-SCREEN COMMENT 5(37) text-b05 FOR FIELD pf_cpyl.
SELECTION-SCREEN END OF LINE.
* EOC by GSINGH.
PARAMETERS :p_desc TYPE /psyng/swsodvers-vdesc
MODIF ID lp.
SELECTION-SCREEN END OF BLOCK descb.

SELECTION-SCREEN: END OF BLOCK publishb.

selection-SCREEN : begin of block output with FRAME TITLE text-b10.
  PARAMETERS: p_log  radiobutton group out DEFAULT  'X',
              p_alv  RADIOBUTTON GROUP out.
selection-SCREEN end of block output.

*---Background Block
SELECTION-SCREEN: BEGIN OF BLOCK bgd_o WITH FRAME TITLE text-b11 .
SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN PUSHBUTTON  4(30) text-010 USER-COMMAND scjb
MODIF ID bgd.
SELECTION-SCREEN PUSHBUTTON  40(25) text-009 USER-COMMAND sm37
MODIF ID bgd.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN: END OF BLOCK bgd_o.
