
DATA: UPD_ICDTXT_FUNCTS          TYPE C.
DATA: BEGIN OF ICDTXT_FUNCTS          OCCURS 20.
        INCLUDE STRUCTURE CDTXT.
DATA: END OF ICDTXT_FUNCTS         .

TABLES: */PSYNG/FUNCTION               , /PSYNG/FUNCTION               .
DATA: UPD_PSYNG_FUNCTION                 TYPE C.

TABLES: */PSYNG/FUNCTTRAN              , /PSYNG/FUNCTTRAN              .
DATA: UPD_PSYNG_FUNCTTRAN                TYPE C.

