*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 02/25/2006 at 23:46:29 by user SSANGHA
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /PSYNG/LSWTOP.                     " Global Data
  INCLUDE /PSYNG/LSWUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /PSYNG/LSWF00                           . " subprograms
  INCLUDE /PSYNG/LSWI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
  INCLUDE /PSYNG/LSWF01.                     " Subprograms
  INCLUDE /PSYNG/LSWO01.                     " PBO-Modules
  INCLUDE /PSYNG/LSWI01.                     " PAI-Modules
