REPORT /PSYNG/POSITONHIST_TO_ALV NO STANDARD PAGE HEADING.

*----------------------------------------------------------------------*
* PROGRAM               : /PSYNG/POSITONHIST
* AUTHOR                : Principal Synergy LLC
* RELEASE               : 1.0
* DATE OF RELEASE       : 10/19/2004
* TRANSPORT REQUEST #   :
*----------------------------------------------------------------------*
* COPYRIGHTS Principal Synergy LLC
*
* WARNING:
* THIS COMPUTER PROGRAM IS PROTECTED BY COPYRIGHT LAW AND INTERNATIONAL
* TREATIES. UNAUTHORIZED REPRODUCTION OR DISTRIBUTION IS STRICTLY
* PROHIBITED AND MAY RESULT IN SEVERE CIVIL AND CRIMINAL PENALTIES AND
* WILL BE PROSECUTED TO THE MAXIMUM EXTENT POSSIBLE UNDER THE LAW.
*
*----------------------------------------------------------------------*

TABLES: /PSYNG/HISTORY, /PSYNG/POSITION.

TYPE-POOLS: SLIS.

*Define internal tables.
DATA: BEGIN OF TY_HISTORY,
      HDRFLD LIKE /PSYNG/HISTORY-HDRFLD,
      OLDVAL LIKE /PSYNG/HISTORY-OLDVAL,
      STATUS LIKE /PSYNG/HISTORY-STATUS,
      CREATE_USR LIKE /PSYNG/HISTORY-CREATE_USR,
      CREATE_DAT LIKE /PSYNG/HISTORY-CREATE_DAT,
      CREATE_TIM LIKE /PSYNG/HISTORY-CREATE_TIM,
      OLDVAL1 LIKE /PSYNG/HISTORY-OLDVAL,
      NEWVAL1 LIKE /PSYNG/HISTORY-NEWVAL,
      STATUS1 LIKE /PSYNG/HISTORY-STATUS,
      CREATE_USR1 LIKE /PSYNG/HISTORY-CREATE_USR,
      CREATE_DAT1 LIKE /PSYNG/HISTORY-CREATE_DAT,
      CREATE_TIM1 LIKE /PSYNG/HISTORY-CREATE_TIM,
      OLDVAL2 LIKE /PSYNG/HISTORY-OLDVAL,
      NEWVAL2 LIKE /PSYNG/HISTORY-NEWVAL,
      STATUS2 LIKE /PSYNG/HISTORY-STATUS,
      CREATE_USR2 LIKE /PSYNG/HISTORY-CREATE_USR,
      CREATE_DAT2 LIKE /PSYNG/HISTORY-CREATE_DAT,
      CREATE_TIM2 LIKE /PSYNG/HISTORY-CREATE_TIM,
      END OF TY_HISTORY.

DATA:WA_HISTORY LIKE TY_HISTORY,
     GT_HISTORY LIKE STANDARD TABLE OF TY_HISTORY WITH HEADER LINE
     INITIAL SIZE 0.

*Define fieldcatalog
DATA: T_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV,    "Field Catalog
      G_W_FIELDCAT TYPE SLIS_FIELDCAT_ALV,      "Field Catalog Workarea
      Y_LAYOUT TYPE SLIS_LAYOUT_ALV,          "ALV Report Layout
      T_SORT TYPE SLIS_T_SORTINFO_ALV,
      W_SORT TYPE SLIS_SORTINFO_ALV,
      gs_program like sy-repid,
      gs_variant type disvariant.


*Define Selections Screen
SELECTION-SCREEN: BEGIN OF BLOCK SEL WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS: POSITION FOR /PSYNG/POSITION-POSITIONID.
SELECT-OPTIONS: DATE FOR SY-DATUM.
SELECT-OPTIONS: TIME FOR SY-UZEIT.
SELECT-OPTIONS: USER FOR SY-UNAME.
SELECTION-SCREEN: END OF BLOCK SEL.

*Initializations
INITIALIZATION.
  REFRESH: GT_HISTORY.

*Start of Selection
START-OF-SELECTION.
*BOC UMITTAL SE VF scan changes-25/11/2024

AUTHORITY-CHECK OBJECT 'S_PROGRAM'
       ID 'P_GROUP' FIELD 'SW_SE'
       ID 'P_ACTION' FIELD 'SUBMIT'.
  IF sy-subrc NE 0..
    MESSAGE i108(/psyng/sw) with 'execute ' sy-repid.
    EXIT.
  ENDIF.

*EOC UMITTAL SE VF scan changes-25/11/2024
  PERFORM GET_HISTORY.
  PERFORM BUILD_FIELDCAT.
*  PERFORM BUILD_SORT.
  PERFORM DISPLAY_ALV_OUTPUT.

*&---------------------------------------------------------------------*
*&      Form  GET_HISTORY
*&---------------------------------------------------------------------*
*       Get the Data to Internal Table
*----------------------------------------------------------------------*

FORM GET_HISTORY.

  SELECT * FROM /PSYNG/HISTORY
  WHERE TABNAME = '/PSYNG/POSITION'
  AND   HDRFLD  = 'POSITIONID'
  AND   OLDVAL  IN POSITION
  AND   CREATE_DAT IN DATE
  AND   CREATE_TIM IN TIME
  AND   CREATE_USR IN USER.

    MOVE /PSYNG/HISTORY-OLDVAL TO GT_HISTORY-OLDVAL.
    MOVE /PSYNG/HISTORY-STATUS TO GT_HISTORY-STATUS.
    MOVE /PSYNG/HISTORY-CREATE_USR TO GT_HISTORY-CREATE_USR.
    MOVE /PSYNG/HISTORY-CREATE_DAT TO GT_HISTORY-CREATE_DAT.
    MOVE /PSYNG/HISTORY-CREATE_TIM TO GT_HISTORY-CREATE_TIM.

    SELECT SINGLE * FROM /PSYNG/HISTORY      "#EC CI_SEL_NESTED
     INTO /PSYNG/HISTORY
    WHERE TABNAME = '/PSYNG/POSITION'
    AND   HDRFLD  = /PSYNG/HISTORY-OLDVAL
    AND   DTLFLD  = 'SAPTECHNAME'
    AND   CREATE_DAT = /PSYNG/HISTORY-CREATE_DAT
    AND   CREATE_TIM = /PSYNG/HISTORY-CREATE_TIM
    AND   CREATE_USR = /PSYNG/HISTORY-CREATE_USR.

    IF SY-SUBRC = 0.

      MOVE /PSYNG/HISTORY-OLDVAL TO GT_HISTORY-OLDVAL1.
      MOVE /PSYNG/HISTORY-NEWVAL TO GT_HISTORY-NEWVAL1.
      MOVE /PSYNG/HISTORY-STATUS TO GT_HISTORY-STATUS1.
      MOVE /PSYNG/HISTORY-CREATE_USR TO GT_HISTORY-CREATE_USR1.
      MOVE /PSYNG/HISTORY-CREATE_DAT TO GT_HISTORY-CREATE_DAT1.
      MOVE /PSYNG/HISTORY-CREATE_TIM TO GT_HISTORY-CREATE_TIM1.

    ENDIF.

    SELECT * FROM /PSYNG/HISTORY        "#EC CI_SEL_NESTED
    WHERE TABNAME = '/PSYNG/POSNDET'
    AND   HDRFLD  = /PSYNG/HISTORY-OLDVAL
    AND   CREATE_DAT = /PSYNG/HISTORY-CREATE_DAT
    AND   CREATE_TIM = /PSYNG/HISTORY-CREATE_TIM
    AND   CREATE_USR = /PSYNG/HISTORY-CREATE_USR.

      MOVE /PSYNG/HISTORY-OLDVAL TO GT_HISTORY-OLDVAL2.
      MOVE /PSYNG/HISTORY-NEWVAL TO GT_HISTORY-NEWVAL2.
      MOVE /PSYNG/HISTORY-STATUS TO GT_HISTORY-STATUS2.
      MOVE /PSYNG/HISTORY-CREATE_USR TO GT_HISTORY-CREATE_USR2.
      MOVE /PSYNG/HISTORY-CREATE_DAT TO GT_HISTORY-CREATE_DAT2.
      MOVE /PSYNG/HISTORY-CREATE_TIM TO GT_HISTORY-CREATE_TIM2.

       INSERT TABLE GT_HISTORY.
       CLEAR GT_HISTORY.

    ENDSELECT.

     IF NOT GT_HISTORY IS INITIAL.
       APPEND GT_HISTORY.
       CLEAR GT_HISTORY.
     ENDIF.

  ENDSELECT.

ENDFORM.                    " GET_HISTORY

*---------------------------------------------------------------------*
*       FORM BUILD_FIELDCAT
*---------------------------------------------------------------------*
*       Filling the values to fieldcatalog
*---------------------------------------------------------------------*

FORM BUILD_FIELDCAT.

  REFRESH T_FIELDCAT[].
  CLEAR G_W_FIELDCAT.

  G_W_FIELDCAT-FIELDNAME = 'OLDVAL'.
  G_W_FIELDCAT-TABNAME   = 'GT_HISTORY'.
  G_W_FIELDCAT-SELTEXT_L = 'Position'(007).
  G_W_FIELDCAT-COL_POS = 1.
  G_W_FIELDCAT-EMPHASIZE = 'C100'.
  APPEND G_W_FIELDCAT TO T_FIELDCAT.
  CLEAR G_W_FIELDCAT.

  G_W_FIELDCAT-FIELDNAME = 'STATUS'.
  G_W_FIELDCAT-TABNAME   = 'GT_HISTORY'.
  G_W_FIELDCAT-SELTEXT_L = 'Status'(003).
  G_W_FIELDCAT-COL_POS = 2.
  G_W_FIELDCAT-EMPHASIZE = 'C100'.
  APPEND G_W_FIELDCAT TO T_FIELDCAT.
  CLEAR G_W_FIELDCAT.

  G_W_FIELDCAT-FIELDNAME = 'CREATE_USR'.
  G_W_FIELDCAT-TABNAME   = 'GT_HISTORY'.
  G_W_FIELDCAT-SELTEXT_L = 'User'(004).
  G_W_FIELDCAT-COL_POS = 3.
  G_W_FIELDCAT-EMPHASIZE = 'C100'.
  APPEND G_W_FIELDCAT TO T_FIELDCAT.
  CLEAR G_W_FIELDCAT.

  G_W_FIELDCAT-FIELDNAME = 'CREATE_DAT'.
  G_W_FIELDCAT-TABNAME   = 'GT_HISTORY'.
  G_W_FIELDCAT-SELTEXT_L = 'Date'(005).
  G_W_FIELDCAT-COL_POS = 4.
  G_W_FIELDCAT-EMPHASIZE = 'C100'.
  APPEND G_W_FIELDCAT TO T_FIELDCAT.
  CLEAR G_W_FIELDCAT.

  G_W_FIELDCAT-FIELDNAME = 'CREATE_TIM'.
  G_W_FIELDCAT-TABNAME   = 'GT_HISTORY'.
  G_W_FIELDCAT-SELTEXT_L = 'Time'(006).
  G_W_FIELDCAT-COL_POS = 5.
  G_W_FIELDCAT-EMPHASIZE = 'C100'.
  APPEND G_W_FIELDCAT TO T_FIELDCAT.
  CLEAR G_W_FIELDCAT.

  G_W_FIELDCAT-FIELDNAME = 'OLDVAL1'.
  G_W_FIELDCAT-TABNAME   = 'GT_HISTORY'.
  G_W_FIELDCAT-SELTEXT_L = 'Old Saptechname'(008).
  G_W_FIELDCAT-COL_POS = 6.
  G_W_FIELDCAT-EMPHASIZE = 'C400'.
  APPEND G_W_FIELDCAT TO T_FIELDCAT.
  CLEAR G_W_FIELDCAT.

  G_W_FIELDCAT-FIELDNAME = 'NEWVAL1'.
  G_W_FIELDCAT-TABNAME   = 'GT_HISTORY'.
  G_W_FIELDCAT-SELTEXT_L = 'New Saptechname'(009).
  G_W_FIELDCAT-COL_POS = 7.
  G_W_FIELDCAT-EMPHASIZE = 'C400'.
  APPEND G_W_FIELDCAT TO T_FIELDCAT.
  CLEAR G_W_FIELDCAT.

  G_W_FIELDCAT-FIELDNAME = 'STATUS1'.
  G_W_FIELDCAT-TABNAME   = 'GT_HISTORY'.
  G_W_FIELDCAT-SELTEXT_L = 'Status'(003).
  G_W_FIELDCAT-COL_POS = 8.
  G_W_FIELDCAT-EMPHASIZE = 'C400'.
  APPEND G_W_FIELDCAT TO T_FIELDCAT.
  CLEAR G_W_FIELDCAT.

  G_W_FIELDCAT-FIELDNAME = 'CREATE_USR1'.
  G_W_FIELDCAT-TABNAME   = 'GT_HISTORY'.
  G_W_FIELDCAT-SELTEXT_L = 'User'(004).
  G_W_FIELDCAT-COL_POS = 9.
  G_W_FIELDCAT-EMPHASIZE = 'C400'.
  APPEND G_W_FIELDCAT TO T_FIELDCAT.
  CLEAR G_W_FIELDCAT.

  G_W_FIELDCAT-FIELDNAME = 'CREATE_DAT1'.
  G_W_FIELDCAT-TABNAME   = 'GT_HISTORY'.
  G_W_FIELDCAT-SELTEXT_L = 'Date'(005).
  G_W_FIELDCAT-COL_POS = 10.
  G_W_FIELDCAT-EMPHASIZE = 'C400'.
  APPEND G_W_FIELDCAT TO T_FIELDCAT.
  CLEAR G_W_FIELDCAT.

  G_W_FIELDCAT-FIELDNAME = 'CREATE_TIM1'.
  G_W_FIELDCAT-TABNAME   = 'GT_HISTORY'.
  G_W_FIELDCAT-SELTEXT_L = 'Time'(006).
  G_W_FIELDCAT-COL_POS = 11.
  G_W_FIELDCAT-EMPHASIZE = 'C400'.
  APPEND G_W_FIELDCAT TO T_FIELDCAT.
  CLEAR G_W_FIELDCAT.

  G_W_FIELDCAT-FIELDNAME = 'OLDVAL2'.
  G_W_FIELDCAT-TABNAME   = 'GT_HISTORY'.
  G_W_FIELDCAT-SELTEXT_L = 'Role'(002).
  G_W_FIELDCAT-COL_POS = 12.
  G_W_FIELDCAT-EMPHASIZE = 'C200'.
  APPEND G_W_FIELDCAT TO T_FIELDCAT.
  CLEAR G_W_FIELDCAT.

  G_W_FIELDCAT-FIELDNAME = 'STATUS2'.
  G_W_FIELDCAT-TABNAME   = 'GT_HISTORY'.
  G_W_FIELDCAT-SELTEXT_L = 'Status'(003).
  G_W_FIELDCAT-COL_POS = 13.
  G_W_FIELDCAT-EMPHASIZE = 'C200'.
  APPEND G_W_FIELDCAT TO T_FIELDCAT.
  CLEAR G_W_FIELDCAT.

  G_W_FIELDCAT-FIELDNAME = 'CREATE_USR2'.
  G_W_FIELDCAT-TABNAME   = 'GT_HISTORY'.
  G_W_FIELDCAT-SELTEXT_L = 'User'(004).
  G_W_FIELDCAT-COL_POS = 14.
  G_W_FIELDCAT-EMPHASIZE = 'C200'.
  APPEND G_W_FIELDCAT TO T_FIELDCAT.
  CLEAR G_W_FIELDCAT.

  G_W_FIELDCAT-FIELDNAME = 'CREATE_DAT2'.
  G_W_FIELDCAT-TABNAME   = 'GT_HISTORY'.
  G_W_FIELDCAT-SELTEXT_L = 'Date'(005).
  G_W_FIELDCAT-COL_POS = 15.
  G_W_FIELDCAT-EMPHASIZE = 'C200'.
  APPEND G_W_FIELDCAT TO T_FIELDCAT.
  CLEAR G_W_FIELDCAT.

  G_W_FIELDCAT-FIELDNAME = 'CREATE_TIM2'.
  G_W_FIELDCAT-TABNAME   = 'GT_HISTORY'.
  G_W_FIELDCAT-SELTEXT_L = 'Time'(006).
  G_W_FIELDCAT-COL_POS = 16.
  G_W_FIELDCAT-EMPHASIZE = 'C200'.
  APPEND G_W_FIELDCAT TO T_FIELDCAT.
  CLEAR G_W_FIELDCAT.

ENDFORM.                    " BUILD_FIELDCAT

*&---------------------------------------------------------------------*
*&      Form  BUILD_SORT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*

FORM BUILD_SORT.

  W_SORT-SPOS = '1'.
  W_SORT-FIELDNAME = 'OLDVAL'.
  W_SORT-TABNAME = 'ITAB'.
  W_SORT-UP = 'X'.
  APPEND W_SORT TO T_SORT.
  CLEAR W_SORT.

*  W_SORT-SPOS = '2'.
*  W_SORT-FIELDNAME = 'OLDVAL1'.
*  W_SORT-TABNAME = 'ITAB'.
*  W_SORT-UP = 'X'.
*  APPEND W_SORT TO T_SORT.
*  CLEAR W_SORT.

ENDFORM.                    " BUILD_SORT

*&---------------------------------------------------------------------*
*&      Form  DISPLAY_ALV_OUTPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*

FORM DISPLAY_ALV_OUTPUT.

  y_layout-zebra = 'X'.
  y_layout-colwidth_optimize = 'X'.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
   EXPORTING
*     I_INTERFACE_CHECK                 = ' '
*     I_BYPASSING_BUFFER                =
*     I_BUFFER_ACTIVE                   = ' '
     I_CALLBACK_PROGRAM                = GS_PROGRAM
*     I_CALLBACK_PF_STATUS_SET          = ' '
*     I_CALLBACK_USER_COMMAND           = ' '
*     I_CALLBACK_TOP_OF_PAGE            = ' '
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME                  =
*     I_BACKGROUND_ID                   = ' '
*     I_GRID_TITLE                      =
*     I_GRID_SETTINGS                   =
     IS_LAYOUT                         = Y_LAYOUT
     IT_FIELDCAT                       = T_FIELDCAT
*     IT_EXCLUDING                      =
*     IT_SPECIAL_GROUPS                 =
     IT_SORT                           = T_SORT
*     IT_FILTER                         =
*     IS_SEL_HIDE                       =
*     I_DEFAULT                         = 'X'
     I_SAVE                            = 'A'
     IS_VARIANT                        = GS_VARIANT
*     IT_EVENTS                         =
*     IT_EVENT_EXIT                     =
*     IS_PRINT                          =
*     IS_REPREP_ID                      =
*     I_SCREEN_START_COLUMN             = 0
*     I_SCREEN_START_LINE               = 0
*     I_SCREEN_END_COLUMN               = 0
*     I_SCREEN_END_LINE                 = 0
*     IT_ALV_GRAPHICS                   =
*     IT_ADD_FIELDCAT                   =
*     IT_HYPERLINK                      =
*     I_HTML_HEIGHT_TOP                 =
*     I_HTML_HEIGHT_END                 =
*     IT_EXCEPT_QINFO                   =
*   IMPORTING
*     E_EXIT_CAUSED_BY_CALLER           =
*     ES_EXIT_CAUSED_BY_USER            =
    TABLES
      T_OUTTAB                          = GT_HISTORY[]
   EXCEPTIONS
     PROGRAM_ERROR                     = 1
     OTHERS                            = 2
            .
  IF SY-SUBRC <> 0.
 MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.
ENDFORM.                    " DISPLAY_ALV_OUTPUT
