FUNCTION /psyng/sw_032 .
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(I_VRSIO) TYPE  /PSYNG/SODVRSIO OPTIONAL
*"     VALUE(I_ENHANC) TYPE  FLAG DEFAULT ' '
*"     VALUE(I_ORGCHK) TYPE  FLAG OPTIONAL
*"     VALUE(I_COMBOS) TYPE  FLAG DEFAULT ''
*"  TABLES
*"      IT_USER STRUCTURE  /PSYNG/RANGE_BNAME OPTIONAL
*"      ET_POLAR STRUCTURE  /PSYNG/SW_ROLE_POLAR OPTIONAL
*"      ET_COMBOS STRUCTURE  /PSYNG/SW_ROLE_POLAR_COMBO OPTIONAL
*"      ET_COMBO_USERS STRUCTURE  /PSYNG/SW_ROLE_POLAR_COMBO_USR
*"       OPTIONAL
*"      IT_CONFLICT STRUCTURE  /PSYNG/CONFLICT OPTIONAL
*"      IT_CONFDET STRUCTURE  /PSYNG/CONFDET OPTIONAL
*"      IT_FUNCTTRAN STRUCTURE  /PSYNG/FUNCTTRAN OPTIONAL
*"      IT_FAOBJ STRUCTURE  /PSYNG/FAOBJ2 OPTIONAL
*"      IT_SWSODORGM STRUCTURE  /PSYNG/SWSODORGM OPTIONAL
*"      IT_TCODES STRUCTURE  /PSYNG/SW_PAR_TCODE_OUTPUT OPTIONAL
*"----------------------------------------------------------------------
*--> BOC SE VF Scan changes - UMITTAL - 02/12/24
CONSTANTS: lc_fname TYPE rs38l_fnam VALUE '/PSYNG/SW_032'.
*  S_RFC AUTHORITY CHECK
  AUTHORITY-CHECK OBJECT 'S_RFC'
        ID 'RFC_TYPE' FIELD 'FUNC'
        ID 'RFC_NAME' FIELD lc_fname
        ID 'ACTVT' FIELD '16'.
  IF sy-subrc <> 0.
    MESSAGE e089(/psyng/sw) WITH lc_fname.
  ENDIF.

*--> EOC SO VF Scan changes - UMITTAL - 02/12/24
MESSAGE e002(/psyng/sw) WITH 'Function Module /PSYNG/SW_032 is obsolete'.

ENDFUNCTION.
