FUNCTION-POOL /psyng/sw_bridge.             "MESSAGE-ID ..

INCLUDE /psyng/sw_http_tools.

TYPES:

  BEGIN OF ty_pbridge_req_con,
    ruleset_id TYPE string,
    pageoffset TYPE string,
    pagesize   TYPE string,
  END OF ty_pbridge_req_con,

  BEGIN OF ty_api_rulset_req,
    pageoffset TYPE string,
    pagesize   TYPE string,
    END OF ty_api_rulset_req,

  BEGIN OF ty_pbridge_res_con,
    row_count   TYPE string,
    conid       TYPE string,
    description TYPE string,
    imp         TYPE string,
    busarea     TYPE string,
    inactive    TYPE string,
  END OF ty_pbridge_res_con,

  BEGIN OF ty_res_pbridge_con_txt,
    row_count   TYPE string,
    conid       TYPE string,
    text        TYPE string,
  END OF ty_res_pbridge_con_txt,

  BEGIN OF ty_pbridge_res_con_details,
    row_count   TYPE string,
    conid       TYPE string,
    functionid  TYPE string,
  END OF ty_pbridge_res_con_details,

  BEGIN OF ty_req_pbridge_fun,
    ruleset_id TYPE string,
    pageoffset TYPE string,
    pagesize   TYPE string,
  END OF ty_req_pbridge_fun,

  BEGIN OF ty_req_pbridge_fun_detail,
    ruleset_id TYPE string,
    systemid   TYPE string,
    pageoffset TYPE string,
    pagesize   TYPE string,
  END OF ty_req_pbridge_fun_detail,

  BEGIN OF ty_req_pbridge_fun_obj,
    ruleset_id TYPE string,
    systemid   TYPE string,
    pageoffset TYPE string,
    pagesize   TYPE string,
  END OF ty_req_pbridge_fun_obj,

  BEGIN OF ty_req_pbridge_incmp_obj,
    systemid   TYPE string,
    pageoffset TYPE string,
    pagesize   TYPE string,
  END OF ty_req_pbridge_incmp_obj,

  BEGIN OF ty_res_pbridge_incmp_obj,
    row_count   TYPE string,
    issuelocation TYPE string,
    issue   TYPE string,
  END OF ty_res_pbridge_incmp_obj,

  BEGIN OF ty_res_pbridge_fun,
    row_count TYPE string,
    function TYPE string,
    description TYPE string,
  END OF ty_res_pbridge_fun,

  BEGIN OF ty_res_pbridge_fun_detail,
    row_count TYPE string,
    functionid TYPE string,
    tcode TYPE string,
  END OF ty_res_pbridge_fun_detail,

  BEGIN OF ty_res_pbridge_fun_obj,
    row_count TYPE string,
    funid TYPE string,
    tcode TYPE string,
    act_mod_val type string,
    object TYPE string,
    valueset TYPE string,
    field TYPE string,
    val_from TYPE string,
    val_to TYPE string,
    obj_or TYPE string,
    fld_and TYPE string,
  END OF ty_res_pbridge_fun_obj,

  BEGIN OF ty_fileupld,
    filename TYPE string,
    content TYPE string,
  END OF ty_fileupld,

  BEGIN OF ty_schema_req,
    api_key TYPE string,
    fileuploads TYPE TABLE OF ty_fileupld WITH NON-UNIQUE DEFAULT KEY,
  END OF ty_schema_req,

  BEGIN OF ty_actions,
    timestamp            TYPE string,
    action               TYPE string,
    targetsystem         TYPE string,
    formatedinstructions TYPE string,
    errormessage         TYPE string,
    callsucceeded         TYPE string,
  END OF ty_actions,

  BEGIN OF ty_schema_res,
    instance TYPE string,
    risks    TYPE TABLE OF string WITH NON-UNIQUE DEFAULT KEY,
    callslog TYPE TABLE OF string WITH NON-UNIQUE DEFAULT KEY,
    actions  TYPE TABLE OF ty_actions WITH NON-UNIQUE DEFAULT KEY,
  END OF ty_schema_res,

  BEGIN OF ty_actvt_grp_req,
    api_key TYPE string,
    fileuploads TYPE TABLE OF ty_fileupld WITH NON-UNIQUE DEFAULT KEY,
  END OF ty_actvt_grp_req,

  BEGIN OF ty_actvt_grp_res,
    instance TYPE string,
    risks    TYPE TABLE OF string WITH NON-UNIQUE DEFAULT KEY,
    callslog TYPE TABLE OF string WITH NON-UNIQUE DEFAULT KEY,
    actions  TYPE TABLE OF ty_actions WITH NON-UNIQUE DEFAULT KEY,
  END OF ty_actvt_grp_res,

  BEGIN OF ty_rules_req,
    api_key TYPE string,
    fileuploads TYPE TABLE OF ty_fileupld WITH NON-UNIQUE DEFAULT KEY,
    useoveridemethod TYPE abap_bool,
  END OF ty_rules_req,

  BEGIN OF ty_rules_res,
    instance TYPE string,
    risks    TYPE TABLE OF string WITH NON-UNIQUE DEFAULT KEY,
    callslog TYPE TABLE OF string WITH NON-UNIQUE DEFAULT KEY,
    actions  TYPE TABLE OF ty_actions WITH NON-UNIQUE DEFAULT KEY,
  END OF ty_rules_res,

  BEGIN OF ty_actvt_mod_val_req,
    api_key TYPE string,
    fileuploads TYPE TABLE OF ty_fileupld WITH NON-UNIQUE DEFAULT KEY,
  END OF ty_actvt_mod_val_req,

  BEGIN OF ty_actvt_mod_val_res,
    instance TYPE string,
    risks    TYPE TABLE OF string WITH NON-UNIQUE DEFAULT KEY,
    callslog TYPE TABLE OF string WITH NON-UNIQUE DEFAULT KEY,
    actions  TYPE TABLE OF ty_actions WITH NON-UNIQUE DEFAULT KEY,
  END OF ty_actvt_mod_val_res,

  BEGIN OF ty_sd_actvt_mod_req,
    api_key TYPE string,
    systemname TYPE string,
    fileuploads TYPE TABLE OF ty_fileupld WITH NON-UNIQUE DEFAULT KEY,
    useoveridemethod TYPE string,
 END OF ty_sd_actvt_mod_req,

  BEGIN OF ty_sd_actvt_mod_res,
    instance TYPE string,
    risks    TYPE TABLE OF string WITH NON-UNIQUE DEFAULT KEY,
    callslog TYPE TABLE OF string WITH NON-UNIQUE DEFAULT KEY,
    actions  TYPE TABLE OF ty_actions WITH NON-UNIQUE DEFAULT KEY,
    END OF ty_sd_actvt_mod_res,

  BEGIN OF ty_sd_grp_cmp_req,
    api_key TYPE string,
    systemname TYPE string,
    fileuploads TYPE TABLE OF ty_fileupld WITH NON-UNIQUE DEFAULT KEY,
    useoveridemethod TYPE string,
 END OF ty_sd_grp_cmp_req,

  BEGIN OF ty_sd_grp_cmp_res,
    instance TYPE string,
    risks    TYPE TABLE OF string WITH NON-UNIQUE DEFAULT KEY,
    callslog TYPE TABLE OF string WITH NON-UNIQUE DEFAULT KEY,
    actions  TYPE TABLE OF ty_actions WITH NON-UNIQUE DEFAULT KEY,
   END OF ty_sd_grp_cmp_res,

  BEGIN OF ty_pbridge_systems,
    row_count           TYPE string,
    systemid            TYPE string,
    systemname          TYPE string,
    systemtype          TYPE string,
    friendlydescription TYPE string,
    isactive            TYPE string,
  END OF ty_pbridge_systems,

  BEGIN OF ty_req_system,
    systemlow  TYPE string,
    systemhigh TYPE string,
    pageoffset TYPE string,
    pagesize   TYPE string,
  END OF ty_req_system,

  BEGIN OF ty_api_ruleset_res,
    row_count TYPE string,
    ruleset_id TYPE string,
    description TYPE string,
    inactive TYPE string,
    END OF ty_api_ruleset_res,

  BEGIN OF ty_req_body_sysdep,
    systemid   TYPE string,
    pageoffset TYPE string,
    pagesize   TYPE string,
  END OF ty_req_body_sysdep,

  BEGIN OF ty_mcdef,
    title TYPE string,
    short_des TYPE string,
    long_des TYPE string,
    procedure TYPE string,
    auto_lev TYPE string,
    rpt_send_auto TYPE string,
    ctl_time_scope TYPE string,
    performer TYPE string,
    owner TYPE string,
    email_msg_temp TYPE string,
    bpw TYPE string,
    rsc TYPE string,
    END OF ty_mcdef,

    BEGIN OF ty_mcassign,
    empid TYPE string,
    comb_name TYPE string,
    aprvr TYPE string,
    aprvr_res TYPE string,
    date_from TYPE string,
    date_to TYPE string,
    END OF ty_mcassign,

    BEGIN OF ty_csv,
line TYPE c LENGTH 10000,
END OF ty_csv.

TYPES : tt_pbridge_con TYPE TABLE OF /psyng/api_conf,
        tt_pbridge_con_txt TYPE TABLE OF /psyng/api_conf_txt,
        tt_pbridge_con_detail TYPE TABLE OF /psyng/api_conf_details,
        tt_pbridge_fun TYPE TABLE OF /psyng/pbridge_fun,
        tt_pbridge_fun_detail TYPE TABLE OF /psyng/pbridge_func_detail,
        tt_pbridge_fun_obj TYPE TABLE OF /psyng/sw_pbridge_fun_obj,
        tt_mcdef TYPE TABLE OF ty_mcdef,
        tt_csv TYPE TABLE OF ty_csv,
        tt_mcassign TYPE TABLE OF ty_mcassign.

DATA  :
  g_host        TYPE string,
  g_port        TYPE string,
  g_scheme      TYPE i,
  g_username    TYPE string,
  g_password    TYPE string,
  g_total_rows  TYPE i,
  g_plcvrs      TYPE /psyng/sw_plc_ruleset.

CONSTANTS: co_password_length           TYPE i  VALUE 40,
            co_number_of_characters     TYPE i  VALUE 94,
            co_password_characters(94)  TYPE c VALUE
         ' !"#$%&()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQ' &
         'RSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~',

         co_key(40)                  TYPE c  VALUE
        'WzAu=GM?pLrU&N\`EF!@mBbg K/nc)e;SvR+Daw[',
        g_endpoint TYPE string VALUE
        '/app/api/reportrun/postrunreport?type=custom&name='.
