REPORT /PSYNG/FUNCTHIST NO STANDARD PAGE HEADING LINE-SIZE 255.
*----------------------------------------------------------------------
*
* PROGRAM               : /PSYNG/FUNCTHIST
* AUTHOR                : Principal Synergy LLC
* RELEASE               : 1.0
*----------------------------------------------------------------------*
*
* COPYRIGHTS Principal Synergy LLC
*
*
* WARNING:
* THIS COMPUTER PROGRAM IS PROTECTED BY COPYRIGHT LAW AND INTERNATIONAL
* TREATIES. UNAUTHORIZED REPRODUCTION OR DISTRIBUTION IS STRICTLY
* PROHIBITED AND MAY RESULT IN SEVERE CIVIL AND CRIMINAL PENALTIES AND
* WILL BE PROSECUTED TO THE MAXIMUM EXTENT POSSIBLE UNDER THE LAW.
*
*----------------------------------------------------------------------*
TABLES: /PSYNG/HISTORY, /PSYNG/FUNCTION.

*Change code
TYPE-POOLS: SLIS. "Define Type-Pool


DATA: V_ALV_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV,  "Field Catalog
      W_FIELDCAT TYPE SLIS_FIELDCAT_ALV,        "Field Catalog Workarea
      Y_LAYOUT TYPE SLIS_LAYOUT_ALV,            "ALV Report Layout
      I_KEYINFO TYPE SLIS_KEYINFO_ALV,
      L_SORT TYPE SLIS_T_SORTINFO_ALV,
      W_SORT TYPE SLIS_SORTINFO_ALV,
      gs_program like sy-repid,
      gs_variant type disvariant.

*end
SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-004.
SELECT-OPTIONS:  FUNCTION FOR /PSYNG/FUNCTION-FUNCTION.
PARAMETERS    :  SODVRSIO LIKE /PSYNG/FUNCTION-VRSIO.
SELECT-OPTIONS : DATE FOR SY-DATUM,
                 TIME FOR SY-UZEIT,
                 USER FOR SY-UNAME.
SELECTION-SCREEN: END OF BLOCK B1.

*Define Internal Tables
DATA: BEGIN OF LT_HIST OCCURS 0,
      OLDVAL LIKE /PSYNG/HISTORY-OLDVAL,
      STATUS LIKE /PSYNG/HISTORY-STATUS,
      CREATE_USR LIKE /PSYNG/HISTORY-CREATE_USR,
      CREATE_DAT LIKE /PSYNG/HISTORY-CREATE_DAT,
      CREATE_TIM LIKE /PSYNG/HISTORY-CREATE_TIM,
      END OF LT_HIST,

      BEGIN OF LT_TRAN OCCURS 0,
*      HDRFLD LIKE /PSYNG/HISTORY-HDRFLD,
      OLDVAL LIKE /PSYNG/HISTORY-OLDVAL,
      NEWVAL LIKE /PSYNG/HISTORY-NEWVAL,
      STATUS LIKE /PSYNG/HISTORY-STATUS,
      CREATE_USR LIKE /PSYNG/HISTORY-CREATE_USR,
      CREATE_DAT LIKE /PSYNG/HISTORY-CREATE_DAT,
      CREATE_TIM LIKE /PSYNG/HISTORY-CREATE_TIM,
      END OF LT_TRAN,

      BEGIN OF LT_TRAN_T OCCURS 0,
      OLDVAL LIKE /PSYNG/HISTORY-OLDVAL,
*      OLDVAL1 LIKE /PSYNG/HISTORY-OLDVAL,
      NEWVAL LIKE /PSYNG/HISTORY-NEWVAL,
      STATUS LIKE /PSYNG/HISTORY-STATUS,
      CREATE_USR LIKE /PSYNG/HISTORY-CREATE_USR,
      CREATE_DAT LIKE /PSYNG/HISTORY-CREATE_DAT,
      CREATE_TIM LIKE /PSYNG/HISTORY-CREATE_TIM,
      END OF LT_TRAN_T.

START-OF-SELECTION.
*BOC UMITTAL SE VF scan changes-25/11/2024

AUTHORITY-CHECK OBJECT 'S_PROGRAM'
       ID 'P_GROUP' FIELD 'SW_SE'
       ID 'P_ACTION' FIELD 'SUBMIT'.
  IF sy-subrc NE 0..
    MESSAGE i108(/psyng/sw) with 'execute ' sy-repid.
    EXIT.
  ENDIF.

*EOC UMITTAL SE VF scan changes-25/11/2024
  gs_program = sy-repid.
  SELECT OLDVAL STATUS CREATE_USR CREATE_DAT CREATE_TIM FROM
  /PSYNG/HISTORY INTO TABLE LT_HIST
      WHERE TABNAME = '/PSYNG/FUNCTION'
      AND   OLDVAL  IN FUNCTION
      AND   CREATE_DAT IN DATE
      AND   CREATE_TIM IN TIME
      AND   VRSIO      =  SODVRSIO
      AND   CREATE_USR IN USER.


  IF NOT LT_HIST[] IS INITIAL.


    SELECT OLDVAL NEWVAL STATUS CREATE_USR CREATE_DAT CREATE_TIM FROM
              /PSYNG/HISTORY INTO CORRESPONDING FIELDS OF TABLE LT_TRAN
                    FOR ALL ENTRIES IN LT_HIST
                    WHERE TABNAME = '/PSYNG/FUNCTTRAN'
                        AND   HDRFLD  = LT_HIST-OLDVAL
                        AND   CREATE_DAT = LT_HIST-CREATE_DAT
                        AND   CREATE_TIM = LT_HIST-CREATE_TIM
                        AND   VRSIO      = SODVRSIO
                        AND   CREATE_USR = LT_HIST-CREATE_USR.

  ENDIF.


  LOOP AT LT_hist.
    LOOP AT LT_TRAN WHERE OLDVAL = LT_HIST-OLDVAL.
      MOVE-CORRESPONDING LT_HIST TO LT_TRAN_T.
      APPEND LT_TRAN_T.
      CLEAR LT_TRAN_T.
      MOVE-CORRESPONDING LT_TRAN TO LT_TRAN_T.
      APPEND LT_TRAN_T.
      CLEAR LT_TRAN_T.
    ENDLOOP.
  ENDLOOP.



  SORT LT_TRAN_T BY OLDVAL.

PERFORM BUILD_FIELDCAT.

PERFORM BUILD_SORT.

CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
  EXPORTING
*   I_INTERFACE_CHECK                 = ' '
*   I_BYPASSING_BUFFER                =
*   I_BUFFER_ACTIVE                   = ' '
   I_CALLBACK_PROGRAM                = gs_program
   IT_FIELDCAT                       = V_ALV_FIELDCAT
*   IT_EXCLUDING                      =
*   IT_SPECIAL_GROUPS                 =
*   IT_SORT                           =
*   IT_FILTER                         =
*   IS_SEL_HIDE                       =
*   I_DEFAULT                         = 'X'
   I_SAVE                            = 'A'
   IS_VARIANT                        = gs_variant
  TABLES
    T_OUTTAB                          = LT_TRAN_T[]
 EXCEPTIONS
   PROGRAM_ERROR                     = 1
   OTHERS                            = 2.
IF SY-SUBRC <> 0.
 MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ENDIF.



  COMMIT WORK.



*&---------------------------------------------------------------------*
*&      Form  BUILD_FIELDCAT
*&---------------------------------------------------------------------*
*       GET BUILD FIELDCATALOG
*----------------------------------------------------------------------*
FORM BUILD_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'OLDVAL'.
  W_FIELDCAT-TABNAME   = 'LT_TRAN_T'.
  W_FIELDCAT-SELTEXT_L = 'Function ID'(005).
  W_FIELDCAT-COL_POS = 1.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'STATUS'.
  W_FIELDCAT-TABNAME   = 'LT_TRAN_T'.
  W_FIELDCAT-SELTEXT_L = 'Status'(006).
  W_FIELDCAT-COL_POS = 2.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.


  W_FIELDCAT-FIELDNAME = 'CREATE_USR'.
  W_FIELDCAT-TABNAME   = 'LT_TRAN_T'.
  W_FIELDCAT-SELTEXT_L = 'Create User'(007).
  W_FIELDCAT-COL_POS = 3.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'CREATE_DAT'.
  W_FIELDCAT-SELTEXT_L = 'Create Date'(008).
  W_FIELDCAT-TABNAME   = 'LT_TRAN_T'.
  W_FIELDCAT-COL_POS = 4.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'CREATE_TIM'.
  W_FIELDCAT-SELTEXT_L = 'Create Time'(009).
  W_FIELDCAT-TABNAME   = 'LT_TRAN_T'.
  W_FIELDCAT-COL_POS = 5.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'OLDVAL'.
  W_FIELDCAT-SELTEXT_L = 'Transaction'(010).
  W_FIELDCAT-TABNAME   = 'LT_TRAN_T'.
  W_FIELDCAT-COL_POS = 6.
*  L_SORT-UP = 'X'.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'NEWVAL'.
  W_FIELDCAT-SELTEXT_L = 'New Value'(011).
  W_FIELDCAT-TABNAME   = 'LT_TRAN_T'.
  W_FIELDCAT-COL_POS = 7.
*  L_SORT-UP = 'X'.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'STATUS'.
  W_FIELDCAT-TABNAME   = 'LT_TRAN_T'.
  W_FIELDCAT-SELTEXT_L = 'Status'(006).
  W_FIELDCAT-COL_POS = 8.
*  L_SORT-UP = 'X'.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'CREATE_USR'.
  W_FIELDCAT-TABNAME   = 'LT_TRAN_T'.
  W_FIELDCAT-SELTEXT_L = 'Create User'(007).
  W_FIELDCAT-COL_POS = 9.
*  L_SORT-UP = 'X'.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'CREATE_DAT'.
  W_FIELDCAT-SELTEXT_L = 'Create Date'(008).
  W_FIELDCAT-TABNAME   = 'LT_TRAN_T'.
  W_FIELDCAT-COL_POS = 10.
*  L_SORT-UP = 'X'.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'CREATE_TIM'.
  W_FIELDCAT-SELTEXT_L = 'Create Time'(009).
  W_FIELDCAT-TABNAME   = 'LT_TRAN_T'.
  W_FIELDCAT-COL_POS = 11.
*  L_SORT-UP = 'X'.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.


ENDFORM.                    " BULILD_FIELDCAT



*&---------------------------------------------------------------------*
*&      Form  BUILD_SORT
*&---------------------------------------------------------------------*
*       GET FILL SORT TABLE
*----------------------------------------------------------------------*

FORM BUILD_SORT.

W_SORT-SPOS = '1'.
W_SORT-FIELDNAME = 'OLDVAL'.
W_SORT-TABNAME = 'LT_TRAN_T'.
W_SORT-UP = 'X'.
APPEND W_SORT TO L_SORT.
CLEAR W_SORT.

W_SORT-SPOS = '2'.
W_SORT-FIELDNAME = 'STATUS'.
W_SORT-TABNAME = 'LT_TRAN_T'.
W_SORT-UP = 'X'.
APPEND W_SORT TO L_SORT.
CLEAR W_SORT.

W_SORT-SPOS = '3'.
W_SORT-FIELDNAME = 'CREATE_USR'.
W_SORT-TABNAME = 'LT_TRAN_T'.
W_SORT-UP = 'X'.
APPEND W_SORT TO L_SORT.
CLEAR W_SORT.

W_SORT-SPOS = '4'.
W_SORT-FIELDNAME = 'CREATE_DAT'.
W_SORT-TABNAME = 'LT_TRAN_T'.
W_SORT-UP = 'X'.
APPEND W_SORT TO L_SORT.
CLEAR W_SORT.

W_SORT-SPOS = '5'.
W_SORT-FIELDNAME = 'CREATE_TIM'.
W_SORT-TABNAME = 'LT_TRAN_T'.
W_SORT-UP = 'X'.
APPEND W_SORT TO L_SORT.
CLEAR W_SORT.

W_SORT-SPOS = '6'.
W_SORT-FIELDNAME = 'OLDVAL'.
W_SORT-TABNAME = 'LT_TRAN_T'.
W_SORT-UP = 'X'.
APPEND W_SORT TO L_SORT.
CLEAR W_SORT.

W_SORT-SPOS = '7'.
W_SORT-FIELDNAME = 'NEWVAL'.
W_SORT-TABNAME = 'LT_TRAN_T'.
W_SORT-UP = 'X'.
APPEND W_SORT TO L_SORT.
CLEAR W_SORT.

W_SORT-SPOS = '8'.
W_SORT-FIELDNAME = 'STATUS'.
W_SORT-TABNAME = 'LT_TRAN_T'.
W_SORT-UP = 'X'.
APPEND W_SORT TO L_SORT.
CLEAR W_SORT.

W_SORT-SPOS = '9'.
W_SORT-FIELDNAME = 'CREATE_USR'.
W_SORT-TABNAME = 'LT_TRAN_T'.
W_SORT-UP = 'X'.
APPEND W_SORT TO L_SORT.
CLEAR W_SORT.

W_SORT-SPOS = '10'.
W_SORT-FIELDNAME = 'CREATE_DAT'.
W_SORT-TABNAME = 'LT_TRAN_T'.
W_SORT-UP = 'X'.
APPEND W_SORT TO L_SORT.
CLEAR W_SORT.

W_SORT-SPOS = '11'.
W_SORT-FIELDNAME = 'CREATE_TIM'.
W_SORT-TABNAME = 'LT_TRAN_T'.
W_SORT-UP = 'X'.
APPEND W_SORT TO L_SORT.
CLEAR W_SORT.

ENDFORM.                    " BUILD_SORT
