*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*   generation date: 19.11.2019 at 00:51:19 by user DDHIMAN
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE /PSYNG/LSW_TABTOP.                 " Global Data
  INCLUDE /PSYNG/LSW_TABUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE /PSYNG/LSW_TABF00                       . " subprograms
  INCLUDE /PSYNG/LSW_TABI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE /PSYNG/LSW_TABF...                 " Subprograms
* INCLUDE /PSYNG/LSW_TABO...                 " PBO-Modules
* INCLUDE /PSYNG/LSW_TABI...                 " PAI-Modules
