REPORT /PSYNG/ROLETXNHIST_TO_ALV NO STANDARD PAGE HEADING.
*----------------------------------------------------------------------
*
* PROGRAM               : /PSYNG/ROLETXNHIST
* AUTHOR                : Principal Synergy LLC
* RELEASE               : 1.0
* DATE OF RELEASE       : 10/19/2004
* TRANSPORT REQUEST #   :
*----------------------------------------------------------------------*
*
* COPYRIGHTS Principal Synergy LLC
*
*
* WARNING:
* THIS COMPUTER PROGRAM IS PROTECTED BY COPYRIGHT LAW AND INTERNATIONAL
* TREATIES. UNAUTHORIZED REPRODUCTION OR DISTRIBUTION IS STRICTLY
* PROHIBITED AND MAY RESULT IN SEVERE CIVIL AND CRIMINAL PENALTIES AND
* WILL BE PROSECUTED TO THE MAXIMUM EXTENT POSSIBLE UNDER THE LAW.
*
*----------------------------------------------------------------------*
TABLES: /PSYNG/HISTORY, /PSYNG/ROLEHDR.

*Change code
TYPE-POOLS: SLIS. "Define Type-Pool


DATA: V_ALV_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV,  "Field Catalog
      W_FIELDCAT TYPE SLIS_FIELDCAT_ALV,        "Field Catalog Workarea
      Y_LAYOUT TYPE SLIS_LAYOUT_ALV,            "ALV Report Layout
      I_KEYINFO TYPE SLIS_KEYINFO_ALV.

*end


SELECT-OPTIONS: ROLEID FOR /PSYNG/ROLEHDR-ROLEID.
*PARAMETERS    : SODVRSIO LIKE /PSYNG/ROLEHDR-VRSIO.
SELECT-OPTIONS: DATE FOR SY-DATUM,
                TIME FOR SY-UZEIT,
                USER FOR SY-UNAME.

*Define Internal Tables
DATA: BEGIN OF LT_HIST OCCURS 0,
      OLDVAL LIKE /PSYNG/HISTORY-OLDVAL,
      STATUS LIKE /PSYNG/HISTORY-STATUS,
      CREATE_USR LIKE /PSYNG/HISTORY-CREATE_USR,
      CREATE_DAT LIKE /PSYNG/HISTORY-CREATE_DAT,
      CREATE_TIM LIKE /PSYNG/HISTORY-CREATE_TIM,
      END OF LT_HIST,

      BEGIN OF LT_TRAN OCCURS 0,
      HDRFLD LIKE /PSYNG/HISTORY-HDRFLD,
      OLDVAL LIKE /PSYNG/HISTORY-OLDVAL,
      NEWVAL LIKE /PSYNG/HISTORY-NEWVAL,
      STATUS LIKE /PSYNG/HISTORY-STATUS,
      CREATE_USR LIKE /PSYNG/HISTORY-CREATE_USR,
      CREATE_DAT LIKE /PSYNG/HISTORY-CREATE_DAT,
      CREATE_TIM LIKE /PSYNG/HISTORY-CREATE_TIM,
      END OF LT_TRAN,

      BEGIN OF LT_TRAN_T OCCURS 0,
      OLDVAL LIKE /PSYNG/HISTORY-OLDVAL,
      OLDVAL1 LIKE /PSYNG/HISTORY-OLDVAL,
      NEWVAL LIKE /PSYNG/HISTORY-NEWVAL,
      STATUS LIKE /PSYNG/HISTORY-STATUS,
      CREATE_USR LIKE /PSYNG/HISTORY-CREATE_USR,
      CREATE_DAT LIKE /PSYNG/HISTORY-CREATE_DAT,
      CREATE_TIM LIKE /PSYNG/HISTORY-CREATE_TIM,
      END OF LT_TRAN_T.



START-OF-SELECTION.
*BOC UMITTAL SE VF scan changes-25/11/2024

AUTHORITY-CHECK OBJECT 'S_PROGRAM'
       ID 'P_GROUP' FIELD 'SW_SE'
       ID 'P_ACTION' FIELD 'SUBMIT'.
  IF sy-subrc NE 0..
    MESSAGE i108(/psyng/sw) with 'execute ' sy-repid.
    EXIT.
  ENDIF.

*EOC UMITTAL SE VF scan changes-25/11/2024

  SELECT OLDVAL STATUS CREATE_USR CREATE_DAT CREATE_TIM FROM
         /PSYNG/HISTORY INTO TABLE LT_HIST
         WHERE TABNAME = '/PSYNG/ROLEHDR'
         AND   HDRFLD  = 'RLETXN'
         AND   OLDVAL  IN ROLEID
         AND   CREATE_DAT IN DATE
         AND   CREATE_TIM IN TIME
         AND   CREATE_USR IN USER.

  IF NOT LT_HIST[] IS INITIAL.


SELECT HDRFLD OLDVAL NEWVAL STATUS CREATE_USR CREATE_DAT CREATE_TIM FROM
        /PSYNG/HISTORY INTO CORRESPONDING FIELDS OF TABLE LT_TRAN
        FOR ALL ENTRIES IN LT_HIST
        WHERE TABNAME = '/PSYNG/ROLETRANS'
            AND   HDRFLD  = LT_HIST-OLDVAL
            AND   CREATE_DAT = LT_HIST-CREATE_DAT
            AND   CREATE_TIM = LT_HIST-CREATE_TIM
            AND   CREATE_USR = LT_HIST-CREATE_USR.

  ENDIF.

  LOOP AT LT_TRAN.
    CLEAR LT_TRAN_T.
    MOVE-CORRESPONDING LT_TRAN TO LT_TRAN_T.
    CLEAR: LT_TRAN_T-OLDVAL, LT_TRAN_T-OLDVAL1.
    LT_TRAN_T-OLDVAL = LT_TRAN-HDRFLD.
    LT_TRAN_T-OLDVAL1 = LT_TRAN-OLDVAL.
    APPEND LT_TRAN_T.
  ENDLOOP.



  SORT LT_TRAN_T BY OLDVAL.


  I_KEYINFO-HEADER01 = 'OLDVAL'.

  I_KEYINFO-ITEM01 = 'OLDVAL'.

  I_KEYINFO-HEADER02 = 'CREATE_USR'.

  I_KEYINFO-ITEM02 = 'CREATE_USR'.

  I_KEYINFO-HEADER03 = 'CREATE_DAT'.

  I_KEYINFO-ITEM03 = 'CREATE_DAT'.

  I_KEYINFO-HEADER04 = 'CREATE_TIM'.

  I_KEYINFO-ITEM04 = 'CREATE_TIM'.


  W_FIELDCAT-FIELDNAME = 'OLDVAL'.
  W_FIELDCAT-TABNAME   = 'LT_HIST'.
  W_FIELDCAT-SELTEXT_L = 'FUNCTION ID'.
  W_FIELDCAT-COL_POS = 1.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'STATUS'.
  W_FIELDCAT-TABNAME   = 'LT_HIST'.
  W_FIELDCAT-SELTEXT_L = 'STATUS'.
  W_FIELDCAT-COL_POS = 2.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.


  W_FIELDCAT-FIELDNAME = 'CREATE_USR'.
  W_FIELDCAT-TABNAME   = 'LT_HIST'.
  W_FIELDCAT-SELTEXT_L = 'CREATE_USR'.
  W_FIELDCAT-COL_POS = 3.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'CREATE_DAT'.
  W_FIELDCAT-SELTEXT_L = 'CREATE_DAT'.
  W_FIELDCAT-TABNAME   = 'LT_HIST'.
  W_FIELDCAT-COL_POS = 4.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'CREATE_TIM'.
  W_FIELDCAT-SELTEXT_L = 'CREATE_TIM'.
  W_FIELDCAT-TABNAME   = 'LT_HIST'.
  W_FIELDCAT-COL_POS = 5.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'OLDVAL1'.
  W_FIELDCAT-SELTEXT_L = 'OLDVAL1'.
  W_FIELDCAT-TABNAME   = 'LT_TRAN_T'.
  W_FIELDCAT-COL_POS = 6.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'NEWVAL'.
  W_FIELDCAT-SELTEXT_L = 'NEWVAL'.
  W_FIELDCAT-TABNAME   = 'LT_TRAN_T'.
  W_FIELDCAT-COL_POS = 7.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'STATUS'.
  W_FIELDCAT-TABNAME   = 'LT_TRAN_T'.
  W_FIELDCAT-SELTEXT_L = 'STATUS'.
  W_FIELDCAT-COL_POS = 8.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'CREATE_USR'.
  W_FIELDCAT-TABNAME   = 'LT_TRAN_T'.
  W_FIELDCAT-SELTEXT_L = 'CREATE_USR'.
  W_FIELDCAT-COL_POS = 9.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'CREATE_DAT'.
  W_FIELDCAT-SELTEXT_L = 'CREATE_DAT'.
  W_FIELDCAT-TABNAME   = 'LT_TRAN_T'.
  W_FIELDCAT-COL_POS = 10.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.

  W_FIELDCAT-FIELDNAME = 'CREATE_TIM'.
  W_FIELDCAT-SELTEXT_L = 'CREATE_TIM'.
  W_FIELDCAT-TABNAME   = 'LT_TRAN_T'.
  W_FIELDCAT-COL_POS = 11.
  APPEND W_FIELDCAT TO V_ALV_FIELDCAT.
  CLEAR W_FIELDCAT.


  CALL FUNCTION 'REUSE_ALV_HIERSEQ_LIST_DISPLAY'
    EXPORTING
*   I_INTERFACE_CHECK              = ' '
     I_CALLBACK_PROGRAM             = SY-CPROG
*   I_CALLBACK_PF_STATUS_SET       = ' '
*   I_CALLBACK_USER_COMMAND        = ' '
*   IS_LAYOUT                      =
     IT_FIELDCAT                    = V_ALV_FIELDCAT
*   IT_EXCLUDING                   =
*   IT_SPECIAL_GROUPS              =
*   IT_SORT                        =
*   IT_FILTER                      =
*   IS_SEL_HIDE                    =
*   I_SCREEN_START_COLUMN          = 0
*   I_SCREEN_START_LINE            = 0
*   I_SCREEN_END_COLUMN            = 0
*   I_SCREEN_END_LINE              = 0
*   I_DEFAULT                      = 'X'
*   I_SAVE                         = ' '
*   IS_VARIANT                     =
*   IT_EVENTS                      =
*   IT_EVENT_EXIT                  =
      I_TABNAME_HEADER               = 'LT_HIST'
      I_TABNAME_ITEM                 = 'LT_TRAN_T'
*   I_STRUCTURE_NAME_HEADER        =
*   I_STRUCTURE_NAME_ITEM          =
      IS_KEYINFO                     = I_KEYINFO

*   IS_PRINT                       =
*   IS_REPREP_ID                   =
*   I_BUFFER_ACTIVE                =
*   I_BYPASSING_BUFFER             =
* IMPORTING
*   E_EXIT_CAUSED_BY_CALLER        =
*   ES_EXIT_CAUSED_BY_USER         =
    TABLES
      T_OUTTAB_HEADER                = LT_HIST[]
      T_OUTTAB_ITEM                  = LT_TRAN_T[]
 EXCEPTIONS
   PROGRAM_ERROR                  = 1
   OTHERS                         = 2
            .
  IF SY-SUBRC <> 0.
 MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.
